### ISSUE TITLE
Support condition assertions

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt-kube#4]
Easily check for the presence of a particular `Condition` with `Condition.Type` on a resource and its `Condition.Status` value:

```yaml
tests:
  - name: pod-has-true-ready-condition
    kube:
      get: pods/nginx
      assert:
        conditions:
          ready: true
  - name: pod-ready-condition-either-false-or-unknown
    kube:
      get: pods/nginx
      assert:
        conditions:
          ready:
            - false
            - unknown
```

Note that the `Condition.Type` and `Condition.Status` values shall be compared using case-insensitive matching.
