### ISSUE TITLE
support JSON assertions

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt-kube#5]
JSON assertions are now in `gdt-core` and used in the `gdt-http` plugin. Want to support the same user experience with `gdt-kube` for handling more complicated assertions than the `kube.assert.matches` allows.

Some examples I'm thinking of:

```yaml
tests:
- name: check pod name equals "foo"
  kube:
    get: pods -l app:nginx
    assert:
      len: 1
      json:
        paths:
          - $.metadata.name: foo
- name: check pod has a "Ready" condition with a Status of "True"
  kube:
    get: pods/foo
    assert:
      json:
        paths:
          - $.status.conditions[?(@.type=='Ready')]: True
- name: clusterID field is a UUID 
  kube:
    get: clusters/foo
    assert:
      json:
        path_formats:
          - $.status.clusterID: uuid4
```
