### ISSUE TITLE
Support assertions on state transitions

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt-kube#9]
We want to be able to streamline the assertion of expected state transitions for a resource.

Similar to how #4 adds the ability to assert `Status.Conditions` values, we want test authors to have a pithy way of expressing "Expect to see this resource go through states X and Y but eventually end up in Z".

Perhaps something like this?

```yaml
tests:
  - kube:
      get: pods/nginx
      assert:
        transitions:
          conditions:
            ready:
             - [unknown, false]
             - true
```
